package main;

import java.io.File;
import javax.swing.JOptionPane;
import java.io.IOException;
import javax.xml.XMLConstants;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

/**
 *
 * @author Matias Corazzini (Argentina) matiascorazzini@gmail.com
 *
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    public File ruta;
    File carpeta;

    SetIcono SetIcono = new SetIcono();
    AplicarCambios AplicarCambios = new AplicarCambios();

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setTitle("AoE3EsElProgramaModificador    -Version 0.1- ");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_civ = new javax.swing.JLabel();
        button_Bandera = new javax.swing.JButton();
        jTextField_civNombre = new javax.swing.JTextField();
        button_perro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_explNombre = new javax.swing.JTextField();
        jTextField_perroNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSpinner_nivel = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSpinner_xp = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jSpinner_puntosDesbCartas = new javax.swing.JSpinner();
        jComboBox_Civilizaciones = new javax.swing.JComboBox<>();
        button_BuscarArchivos = new javax.swing.JButton();
        jTextField_BuscarArchivosManual = new javax.swing.JTextField();
        button_info = new javax.swing.JButton();
        button_aplicarCambios = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        button_explorador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jLabel_civ.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N

        button_Bandera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Explorador");

        jLabel2.setText("Perro ");

        jTextField_explNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_explNombreActionPerformed(evt);
            }
        });

        jSpinner_nivel.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinner_nivel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Nivel (Metropolis) ");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Experiencia (xp)");

        jSpinner_xp.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Puntos Desbl. Cartas");

        jSpinner_puntosDesbCartas.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jComboBox_Civilizaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_CivilizacionesActionPerformed(evt);
            }
        });

        button_BuscarArchivos.setText("Busqueda Automatica");
        button_BuscarArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_BuscarArchivosActionPerformed(evt);
            }
        });

        jTextField_BuscarArchivosManual.setText("Ingresar Ruta Manualmente");
        jTextField_BuscarArchivosManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_BuscarArchivosManualActionPerformed(evt);
            }
        });

        button_info.setText("?");
        button_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_infoActionPerformed(evt);
            }
        });

        button_aplicarCambios.setText("Aplicar Cambios");
        button_aplicarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_aplicarCambiosActionPerformed(evt);
            }
        });

        jButton1.setText("Tuto.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Com.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_aplicarCambios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_info))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_civ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_civNombre)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_Bandera, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(jSpinner_puntosDesbCartas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(2, 2, 2)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSpinner_xp, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                    .addComponent(jSpinner_nivel))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox_Civilizaciones, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField_BuscarArchivosManual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                    .addComponent(button_BuscarArchivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(button_perro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(button_explorador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_explNombre)
                                    .addComponent(jTextField_perroNombre)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_civ, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_civNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_Bandera, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8)
                        .addComponent(jTextField_explNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_perroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(button_explorador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_perro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner_nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(button_BuscarArchivos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_BuscarArchivosManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner_xp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Civilizaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_puntosDesbCartas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_aplicarCambios)
                    .addComponent(button_info))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_BuscarArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_BuscarArchivosActionPerformed

        String ruta = System.getProperty("user.home");

        carpeta = new File(ruta + "/Documents/My Games/Age of Empires 3/Savegame");
        File[] archivos = carpeta.listFiles();

        //Verifica que haya archivos
        if (archivos != null) {
            for (int i = 0; i < archivos.length; i++) {

                if (archivos[i].getName().contains("sp_")) {
                    jComboBox_Civilizaciones.addItem(archivos[i].getName());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se ha encontrado la ruta, F ");
        }
    }//GEN-LAST:event_button_BuscarArchivosActionPerformed

    private void jComboBox_CivilizacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_CivilizacionesActionPerformed

        if (evt.getSource() == jComboBox_Civilizaciones) {

            String rutaX = System.getProperty("user.home");

            ruta = new File(rutaX + "/Documents/My Games/Age of Empires 3/Savegame/" + jComboBox_Civilizaciones.getSelectedItem().toString());
            System.out.println(ruta);

            // Instantiate the Factory
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();

            try {
                dbf.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true);

                // parse XML file
                DocumentBuilder db = dbf.newDocumentBuilder();

                Document doc = db.parse(ruta);

                doc.getDocumentElement().normalize();

                //System.out.println("Root Element :" + doc.getDocumentElement().getNodeName());
                //System.out.println("------");
                // get <staff>
                NodeList list = doc.getElementsByTagName("savedhomecity");

                Node item = list.item(0);

                Element nombre = (Element) item;

                for (int temp = 0; temp < list.getLength(); temp++) {

                    Node node = list.item(temp);

                    if (node.getNodeType() == Node.ELEMENT_NODE) {

                        Element element = (Element) node;

                        // get text                  
                        String nombreArchivoV = element.getElementsByTagName("defaultfilename").item(0).getTextContent();
                        String civV = element.getElementsByTagName("civ").item(0).getTextContent();
                        String nombreV = element.getElementsByTagName("name").item(0).getTextContent();
                        String nombreHeroeV = element.getElementsByTagName("heroname").item(0).getTextContent();
                        String nombrePerroV = element.getElementsByTagName("herodogname").item(0).getTextContent();
                        String nivelV = element.getElementsByTagName("level").item(0).getTextContent();
                        String xpV = element.getElementsByTagName("xp").item(0).getTextContent();
                        String puntDesbCartasV = element.getElementsByTagName("skillpoints").item(0).getTextContent();

                        jTextField_civNombre.setText(nombreV);
                        jTextField_explNombre.setText(nombreHeroeV);
                        jTextField_perroNombre.setText(nombrePerroV);

                        jSpinner_nivel.setValue(Integer.parseInt(nivelV));
                        jSpinner_xp.setValue(Integer.parseInt(xpV));
                        jSpinner_puntosDesbCartas.setValue(Integer.parseInt(puntDesbCartasV));

                        button_explorador.setIcon(SetIcono.setIcono("/images/Explorer.png", button_explorador));
                        button_perro.setIcon(SetIcono.setIcono("/images/War_dog.png", button_perro));

                        switch (civV) {
                            case "British":
                                jLabel_civ.setText("Ingleses");
                                button_Bandera.setIcon(SetIcono.setIcono("/images/BritishFlag.png", button_Bandera));
                                System.out.println("These are British");
                                break;

                            case "Spanish":
                                jLabel_civ.setText("Españoles");
                                button_Bandera.setIcon(SetIcono.setIcono("/images/SpanishFlag.png", button_Bandera));
                                System.out.println("These are Spanish");
                                break;

                            case "French":
                                jLabel_civ.setText("Franceses");
                                button_Bandera.setIcon(SetIcono.setIcono("/images/FrenchFlag.png", button_Bandera));
                                System.out.println("These are French");
                                break;

                            case "Portuguese":
                                jLabel_civ.setText("Portugueses");
                                button_Bandera.setIcon(SetIcono.setIcono("/images/PortugueseFlag.png", button_Bandera));
                                System.out.println("These are Portuguese");
                                break;

                            case "Dutch":
                                jLabel_civ.setText("Holandeses");
                                button_Bandera.setIcon(SetIcono.setIcono("/images/DutchFlag.png", button_Bandera));
                                System.out.println("These are Dutch");
                                break;

                            case "Japanese":
                                jLabel_civ.setText("Japoneses");
                                button_Bandera.setIcon(SetIcono.setIcono("/images/JapaneseFlag.png", button_Bandera));
                                System.out.println("These are Japanese");
                                break;

                            case "Germans":
                                jLabel_civ.setText("Alemanes");
                                button_Bandera.setIcon(SetIcono.setIcono("/images/GermanFlag.png", button_Bandera));
                                System.out.println("These are German");
                                break;

                            case "Chinese":
                                jLabel_civ.setText("Chinos");
                                button_Bandera.setIcon(SetIcono.setIcono("/images/ChineseFlag.png", button_Bandera));
                                System.out.println("These are Chinese");
                                break;

                            case "Russians":
                                jLabel_civ.setText("Rusos");
                                button_Bandera.setIcon(SetIcono.setIcono("/images/RussianFlag.png", button_Bandera));
                                System.out.println("These are Russian");
                                break;

                            case "Ottomans":
                                jLabel_civ.setText("Otomanos");
                                button_Bandera.setIcon(SetIcono.setIcono("/images/OttomansFlag.png", button_Bandera));
                                System.out.println("These are Ottomans");
                                break;

                            default:
                                break;
                        }
                    }
                }
            } catch (ParserConfigurationException | SAXException | IOException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jComboBox_CivilizacionesActionPerformed

    private void button_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_infoActionPerformed
        JOptionPane.showMessageDialog(null, "Matias Corazzini te dice:\n\n Al aplicar los cambios, se reescribirá el archivo\n que has seleccionado.\n"
                + " Esto es una BETA desarrollada por un estudiante.\n"
                + " El desarrolador no se hace cargo\n de posibles daños en su metropolis\n Ante cualquier consulta llame al 755-0822\n a ver quien contesta.");
    }//GEN-LAST:event_button_infoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "BIENVENIDO al TUTO pa', aca te voy a encenar a usar mi programa bien perron.\n\n Para comenzar tendras que ingresar la ruta\n"
                + " de tus metropolis guardadas, para eso puedes,\n seleccionar 'Busqueda Automatica', o bien, ingresarla manualmente.\n"
                + " Ej: 'C:\\Users\\pcname\\Documents\\My Games\\Age of Empires 3\\Savegame'\n\n Una vez configurada la ruta, podras desplegar una lista con las\n"
                + " distintas metropolis que tengas y automaticamente se llenaran los\n"
                + " espacios; los cuales podras modificar a tu gusto.\n Una vez hayas realizado los cambios presiona en Aplicar Cambios.\n\n"
                + " Este es un programa de practica por lo que los bugs y problemas\n no van a faltar, el codigo esta abierto a quien quiera modificarlo\n"
                + " en mi GitHub: ");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField_explNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_explNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_explNombreActionPerformed

    private void button_aplicarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_aplicarCambiosActionPerformed

        int input = JOptionPane.showConfirmDialog(null,
                "Esta seguro que quiere aplicar los cambios?"
        );
        //System.out.println(input);
                
        if (input == 0) {           
            AplicarCambios.EscrivirXML(ruta.toString(), jTextField_civNombre.getText(), jTextField_explNombre.getText(), jTextField_perroNombre.getText(),
                    jSpinner_nivel.getValue().toString(), jSpinner_xp.getValue().toString(), jSpinner_puntosDesbCartas.getValue().toString());
        }
    }//GEN-LAST:event_button_aplicarCambiosActionPerformed

    private void jTextField_BuscarArchivosManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_BuscarArchivosManualActionPerformed

    }//GEN-LAST:event_jTextField_BuscarArchivosManualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Bandera;
    private javax.swing.JButton button_BuscarArchivos;
    private javax.swing.JButton button_aplicarCambios;
    private javax.swing.JButton button_explorador;
    private javax.swing.JButton button_info;
    private javax.swing.JButton button_perro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox_Civilizaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_civ;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner jSpinner_nivel;
    private javax.swing.JSpinner jSpinner_puntosDesbCartas;
    private javax.swing.JSpinner jSpinner_xp;
    private javax.swing.JTextField jTextField_BuscarArchivosManual;
    private javax.swing.JTextField jTextField_civNombre;
    private javax.swing.JTextField jTextField_explNombre;
    private javax.swing.JTextField jTextField_perroNombre;
    // End of variables declaration//GEN-END:variables
}
